apiVersion: 1

datasources:
  - name: Elasticsearch
    type: elasticsearch
    access: proxy
    url: http://elasticsearch:9200
    isDefault: true
    editable: false
    jsonData:
      esVersion: 8.0.0
      timeField: timestamp
      maxConcurrentShardRequests: 4
      logMessageField: message
      logLevelField: severity
